language: go

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
- GO111MODULE=on

go:
- 1.11.x

git:
  depth: 1

before_install:
- go get github.com/mitchellh/gox

install:
- # Skip

script:
- go test -v -race ./...
- gox -os="linux" -arch="amd64" -output="bggo" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...
- zip bggo_linux.zip bggo
- gox -os="darwin" -arch="amd64" -output="bggo" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...
- zip bggo_macos.zip bggo
- gox -os="windows" -arch="amd64" -output="bggo" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...
- zip bggo_win.zip bggo

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Uhxg12WgHXsaxt0AUeolPi9UudqfeOzrd3/hBP7Qxpq6fDHrA7BFShKxxeF4bNlXWuSu5k0TUGMQZlpQf81LEP48kBdsuS1Rp0FpH8+56D/YsqAcGet+6+c9lSJWcpoKqe/4R5s6narmKhx4sMjS2DgwQU2+Cyaup6reLQyE+C55dwR6p3Vk6USurAsXUa0cbZbqrbHL9Zoa/Vg6GPi8G5pDaGueBJAWizmQAehrNtfkisD1PXmVdQqFlVEGwU6rlZ7loRZ6JG7SI2iWTHjFm9daJCL8spmdCT/7PG0UqETPK/0G9WNGvgstupYIaZFXz0d3xYsEhLjG40sAZ+afOh0FbYPnfbPJRXq6hI5cyrEFG13joXYihhp8EII58EAjlHn82T57b2Ik0dSj7Itu78lDwtZOZ9/MSX+IlgEQklkVpHFzionMpXNn+UmhExQ7aDPXPQq2+ETL5cncXo3gQqMZ2ZMgttTmUl5fTZ+EWDO7WUGAD+YgMoP5IPoTbt/oesi8Bt7mKHYkoee3cCBxHwgvnHQR7529Gntd31+npWkFdCGn4nm/KoQ/ccvjaODy9BaO3ZIpk8LPMBbfmTZTtZ/0KdIDx7dp4yCIyHRwoJtvkuXkxjYQXH140hqY4Mkv6+w8Gf5TPleD+2K2BYUBEcGFTlqDmw6md0KBBpAcq/s=
  file:
  - bggo_linux.zip
  - bggo_macos.zip
  - bggo_win.zip
  on:
    tags: true